name: Deploy to Production

on:
  push:
    branches: ["main", "master"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send deployment start notification
        shell: cmd
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT }}/sendMessage" -d "chat_id=6135147194" -d "text=🚀 DEPLOYMENT STARTED | Repo: ${{ github.repository }} | Author: ${{ github.actor }} | Commit: ${{ github.sha }}"

      - name: Deploy project using .bat script in project root
        shell: cmd
        run: |
          echo === Running deploy.bat in project root ===
          if exist "deploy.bat" (
            call deploy.bat
          ) else (
            echo ❌ deploy.bat topilmadi! Deployment to'xtatildi.
            exit /b 1
          )

      - name: Send success notification
        if: success()
        shell: cmd
        run: |
          for /f "tokens=2 delims==" %%I in ('wmic os get localdatetime /value') do set datetime=%%I
          set datetime=%datetime:~0,4%-%datetime:~4,2%-%datetime:~6,2% %datetime:~8,2%:%datetime:~10,2%
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT }}/sendMessage" -d "chat_id=6135147194" -d "text=✅ DEPLOYMENT SUCCESS | Repo: ${{ github.repository }} | Commit: ${{ github.sha }} | Time: %datetime%"

      - name: Send failure notification
        if: failure()
        shell: cmd
        run: |
          for /f "tokens=2 delims==" %%I in ('wmic os get localdatetime /value') do set datetime=%%I
          set datetime=%datetime:~0,4%-%datetime:~4,2%-%datetime:~6,2% %datetime:~8,2%:%datetime:~10,2%
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT }}/sendMessage" -d "chat_id=6135147194" -d "text=❌ DEPLOYMENT FAILED | Repo: ${{ github.repository }} | Error: Check GitHub Actions logs | Time: %datetime%"
